
# Assignment Number 6

# Student Information:
# - Bratin Mondal (Roll Number - 21CS10016)
# - Somya Kumar (Roll Number - 21CS30050)


test: tinyC libIO.a
	
	@echo "TestCase 1"
	./tinyC _test_1 < testcases/input/ass6_21CS10016_21CS30050_test_1.c > testcases/output/ass6_21CS10016_21CS30050_quads1.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_1.s -o testcases/output/ass6_21CS10016_21CS30050_test_1.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_1.o -o testcases/output/test1 -L. -lIO -no-pie
	@echo "TestCase 1 Compiled Succesfully\n"

	@echo "TestCase 2"
	./tinyC _test_2 < testcases/input/ass6_21CS10016_21CS30050_test_2.c > testcases/output/ass6_21CS10016_21CS30050_quads2.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_2.s -o testcases/output/ass6_21CS10016_21CS30050_test_2.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_2.o -o testcases/output/test2 -L. -lIO -no-pie
	@echo "TestCase 2 Compiled Succesfully\n"
	
	@echo "TestCase 3"
	./tinyC _test_3 < testcases/input/ass6_21CS10016_21CS30050_test_3.c > testcases/output/ass6_21CS10016_21CS30050_quads3.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_3.s -o testcases/output/ass6_21CS10016_21CS30050_test_3.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_3.o -o testcases/output/test3 -L. -lIO -no-pie
	@echo "TestCase 3 Compiled Succesfully\n"
	
	@echo "TestCase 4"
	./tinyC _test_4 < testcases/input/ass6_21CS10016_21CS30050_test_4.c > testcases/output/ass6_21CS10016_21CS30050_quads4.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_4.s -o testcases/output/ass6_21CS10016_21CS30050_test_4.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_4.o -o testcases/output/test4 -L. -lIO -no-pie
	@echo "TestCase 4 Compiled Succesfully\n"
	
	@echo "TestCase 5"
	./tinyC _test_5 < testcases/input/ass6_21CS10016_21CS30050_test_5.c > testcases/output/ass6_21CS10016_21CS30050_quads5.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_5.s -o testcases/output/ass6_21CS10016_21CS30050_test_5.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_5.o -o testcases/output/test5 -L. -lIO -no-pie
	@echo "TestCase 5 Compiled Succesfully\n"
	
	@echo "TestCase 6"
	./tinyC _test_6 < testcases/input/ass6_21CS10016_21CS30050_test_6.c > testcases/output/ass6_21CS10016_21CS30050_quads6.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_6.s -o testcases/output/ass6_21CS10016_21CS30050_test_6.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_6.o -o testcases/output/test6 -L. -lIO -no-pie
	@echo "TestCase 6 Compiled Succesfully\n"
	
	@echo "TestCase 7"
	./tinyC _test_7 < testcases/input/ass6_21CS10016_21CS30050_test_7.c > testcases/output/ass6_21CS10016_21CS30050_quads7.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_7.s -o testcases/output/ass6_21CS10016_21CS30050_test_7.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_7.o -o testcases/output/test7 -L. -lIO -no-pie
	@echo "TestCase 7 Compiled Succesfully\n"

	@echo "TestCase 8"
	./tinyC _test_8 < testcases/input/ass6_21CS10016_21CS30050_test_8.c > testcases/output/ass6_21CS10016_21CS30050_quads8.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_8.s -o testcases/output/ass6_21CS10016_21CS30050_test_8.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_8.o -o testcases/output/test8 -L. -lIO -no-pie
	@echo "TestCase 8 Compiled Succesfully\n"

	@echo "All TestCases Compiled Succesfully\nMake test1 to test8 to execute individual testcases\n"



test1: tinyC libIO.a
	./tinyC _test_1 < testcases/input/ass6_21CS10016_21CS30050_test_1.c > testcases/output/ass6_21CS10016_21CS30050_quads1.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_1.s -o testcases/output/ass6_21CS10016_21CS30050_test_1.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_1.o -o testcases/output/test1 -L. -lIO -no-pie
	./testcases/output/test1

test2: tinyC libIO.a
	./tinyC _test_2 < testcases/input/ass6_21CS10016_21CS30050_test_2.c > testcases/output/ass6_21CS10016_21CS30050_quads2.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_2.s -o testcases/output/ass6_21CS10016_21CS30050_test_2.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_2.o -o testcases/output/test2 -L. -lIO -no-pie
	./testcases/output/test2

test3: tinyC libIO.a
	./tinyC _test_3 < testcases/input/ass6_21CS10016_21CS30050_test_3.c > testcases/output/ass6_21CS10016_21CS30050_quads3.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_3.s -o testcases/output/ass6_21CS10016_21CS30050_test_3.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_3.o -o testcases/output/test3 -L. -lIO -no-pie
	./testcases/output/test3

test4: tinyC libIO.a
	./tinyC _test_4 < testcases/input/ass6_21CS10016_21CS30050_test_4.c > testcases/output/ass6_21CS10016_21CS30050_quads4.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_4.s -o testcases/output/ass6_21CS10016_21CS30050_test_4.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_4.o -o testcases/output/test4 -L. -lIO -no-pie
	./testcases/output/test4

test5: tinyC libIO.a
	./tinyC _test_5 < testcases/input/ass6_21CS10016_21CS30050_test_5.c > testcases/output/ass6_21CS10016_21CS30050_quads5.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_5.s -o testcases/output/ass6_21CS10016_21CS30050_test_5.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_5.o -o testcases/output/test5 -L. -lIO -no-pie
	./testcases/output/test5

test6: tinyC libIO.a
	./tinyC _test_6 < testcases/input/ass6_21CS10016_21CS30050_test_6.c > testcases/output/ass6_21CS10016_21CS30050_quads6.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_6.s -o testcases/output/ass6_21CS10016_21CS30050_test_6.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_6.o -o testcases/output/test6 -L. -lIO -no-pie
	./testcases/output/test6

test7: tinyC libIO.a
	./tinyC _test_7 < testcases/input/ass6_21CS10016_21CS30050_test_7.c > testcases/output/ass6_21CS10016_21CS30050_quads7.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_7.s -o testcases/output/ass6_21CS10016_21CS30050_test_7.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_7.o -o testcases/output/test7 -L. -lIO -no-pie
	./testcases/output/test7

test8: tinyC libIO.a
	./tinyC _test_8 < testcases/input/ass6_21CS10016_21CS30050_test_8.c > testcases/output/ass6_21CS10016_21CS30050_quads8.out
	gcc -c testcases/output/ass6_21CS10016_21CS30050_test_8.s -o testcases/output/ass6_21CS10016_21CS30050_test_8.o
	gcc testcases/output/ass6_21CS10016_21CS30050_test_8.o -o testcases/output/test8 -L. -lIO -no-pie
	./testcases/output/test8

tinyC: lex.yy.o ass6_21CS10016_21CS30050.tab.o ass6_21CS10016_21CS30050_translator.o ass6_21CS10016_21CS30050_target_translator.o
	g++ lex.yy.o ass6_21CS10016_21CS30050.tab.o ass6_21CS10016_21CS30050_translator.o ass6_21CS10016_21CS30050_target_translator.o -lfl -o tinyC

ass6_21CS10016_21CS30050_target_translator.o: ass6_21CS10016_21CS30050_target_translator.cxx ass6_21CS10016_21CS30050_translator.h
	g++ -c ass6_21CS10016_21CS30050_target_translator.cxx

ass6_21CS10016_21CS30050_translator.o: ass6_21CS10016_21CS30050_translator.cxx ass6_21CS10016_21CS30050_translator.h
	g++ -c ass6_21CS10016_21CS30050_translator.cxx

lex.yy.o: lex.yy.c
	g++ -c lex.yy.c

ass6_21CS10016_21CS30050.tab.o: ass6_21CS10016_21CS30050.tab.c
	g++ -c ass6_21CS10016_21CS30050.tab.c

lex.yy.c: ass6_21CS10016_21CS30050.l ass6_21CS10016_21CS30050.tab.h ass6_21CS10016_21CS30050_translator.h
	flex ass6_21CS10016_21CS30050.l

ass6_21CS10016_21CS30050.tab.c ass6_21CS10016_21CS30050.tab.h : ass6_21CS10016_21CS30050.y
	bison -dv ass6_21CS10016_21CS30050.y

libIO.a: ass2_21CS10016_21CS30050.c 
	gcc -c ass2_21CS10016_21CS30050.c
	ar -rcs libIO.a ass2_21CS10016_21CS30050.o

clean:
	rm -f *.yy.* *.o tinyC *.tab.* *.output libIO.a  testcases/output/*.o testcases/output/test*
